GET http://localhost:3000/api/auth/login

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "name": "alberto3",
}
###
GET http://localhost:3000/api/profile/avatar

###